"""Changed height from ft/inch string to cm float

Revision ID: a0a70f09694f
Revises: 5d216df3df20
Create Date: 2018-08-20 23:28:07.807668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a70f09694f'
down_revision = '5d216df3df20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'height')
    op.add_column('player', sa.Column('height', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'height')
    op.add_column('player', sa.Column('height', sa.String(), nullable=True))
    # ### end Alembic commands ###
