version: 2
jobs:
  build:
    working_directory: ~/aaront/puckdb
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      PUCKDB_DB_HOST: 127.0.0.1
      PUCKDB_DB_PORT: 5432
      PUCKDB_DB_TEST_DATABASE: circle_test
      PUCKDB_DB_USER: root
    docker:
    - image: circleci/python:3.7-rc-stretch
    - image: circleci/postgres:9.6.2
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: circle_test
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-{{ .Revision }}
    - run:
        name: Install Dependencies
        command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .
            pip install -r dev-requirements.txt
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ .Revision }}
        paths:
          - "venv"
    - run:
        name: Running Tests
        command: |
          . venv/bin/activate
          py.test --cov-config .coveragerc --cov-report xml:$CIRCLE_TEST_REPORTS/coverage.xml --cov puckdb --junitxml $CIRCLE_TEST_REPORTS/test-results.xml tests/
    - run: bash <(curl -s https://codecov.io/bash)
    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
